spring:
  application:
    name: wolf-union-app
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include : "*"





server:
  port: 8100

provider:
  application:
    name: wolf-union


